### ISSUE TITLE
Not compatible with ember-cli@2.11.0 / ember-source@2.11.0

### ISSUE THREAD

**Issue by denchen** [laantorchaweb/ember-cli-slick#18]
Using [`ember-cli@2.11.0`](https://github.com/ember-cli/ember-cli/releases/tag/v2.11.0) with this package, I get the following error at bootup:

    Cannot find module '/Users/denchen/git/my-app/bower_components/ember/ember-template-compiler.js'
    Error: Cannot find module '/Users/denchen/git/my-app/bower_components/ember/ember-template-compiler.js'
      at Function.Module._resolveFilename (module.js:325:15)
      at Function.Module._load (module.js:276:25)
      at Module.require (module.js:353:17)
      at require (internal/module.js:12:17)
      at Class.module.exports.htmlbarsOptions (/Users/denchen/git/my-app/node_modules/ember-cli-slick/node_modules/ember-cli-htmlbars/ember-addon-main.js:78:25)
      at Object.registry.add.toTree (/Users/denchen/git/my-app/node_modules/ember-cli-slick/node_modules/ember-cli-htmlbars/ember-addon-main.js:31:36)
      at /Users/denchen/git/my-app/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
      at Array.forEach (native)
      at processPlugins (/Users/denchen/my-app/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
      at module.exports.preprocessTemplates (/Users/denchen/git/my-app/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:161:10)

I believe this is due to this change in `ember-cli@2.11.0`:

> As part of this release we have made the default behavior inclusion of Ember from npm via the ember-source npm package.

Which means that Ember is no longer a Bower dependency / package, and hence `bower_components/ember/ember-template-compiler` would not be available.

**Comment by NickChristensen** [comment]
I got the same thing: https://github.com/laantorchaweb/ember-cli-slick/pull/14#issuecomment-275242719

It's related to the outdated `ember-cli-htmlbars` dependency, and I believe #14 will fix it.

**Comment by laantorchaweb** [comment]
I can confirm that with the latest release `2.0.0` the addon is working on `ember 2.12`. I'm closing this one but please comment if something is not working as expected and sorry for the delay on this.
